# Uncomment the next line to define a global platform for your project
source "https://github.com/ywdonga/XDKitSpecs.git"

platform :ios, '9.0'

target 'XDKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XDKitDemo
  pod "XDUIExtension"
  pod 'Moya' # 请求
  pod 'HandyJSON' # 数据解析
  pod 'RxSwift' # 链式响应式
  pod 'RxCocoa' # 链式响应式
  pod 'RxDataSources' # 列表
  pod 'SnapKit' # 布局
  pod 'TangramKit' # 布局
  pod 'URLNavigator' # 路由

  pod 'LookinServer', :configurations => ['Debug'] # 调试视图查看
  pod 'MLeaksFinder', :git => "https://github.com/Tencent/MLeaksFinder.git", :configurations => ['Debug'] # 内存泄漏检测

end
